name: Parallel-Test
on: push
jobs:
  Add-To-Cart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:adtocart

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
              name: Mocha Awesome Report - Add to Cart
              path: cypress/reports/html

  Register-Test-run:
            runs-on: ubuntu-22.04
            steps:
              - name: Checkout
                uses: actions/checkout@v4
              # Install npm dependencies, cache them correctly
              # and run all Cypress tests
              - name: Cypress run
                uses: cypress-io/github-action@v6
                with:
                  command: npm run test:registertest

              - name: Cypress Test Report
                if: always()
                uses: actions/upload-artifact@v3
                with:
                      name: Mocha Awesome Report- Register Flow
                      path: cypress/reports/html